---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: {{.Values.port}}
    name: {{.Values.port_name}}
  # clusterIP: None
  selector:
    name: {{.Values.port_selector}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.cluster_name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.cluster_name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: {{.Values.cluster_port}}
    name: {{.Values.cluster_port_name}}
  clusterIP: None
  selector:
    app: {{.Values.name}}
