---
name: elasticsearch-chart
version: 0.1.6
description: Elasticsearch for Kubernetes
keywords:
- kraken
- elasticsearch
- logging
- data
home: https://github.com/samsung-cnct/chart-elasticsearch
sources:
- https://github.com/samsung-cnct/chart-elasticsearch
- https://github.com/elastic/elasticsearch
maintainers:
- name: Samsung CNCT
  email: samsung.cloudnative@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
