name: elasticsearch-chart
version: 0.2.1
description: Elasticsearch for Kubernetes
keywords:
- elasticsearch
- logging
- data
home: https://github.com/samsung-cnct/chart-elasticsearch
sources:
- https://github.com/samsung-cnct/chart-elasticsearch
- https://github.com/elastic/elasticsearch
maintainers:
- name: Samsung CNCT OSS Maintainers
  email: oss-maintainer@samsung-cnct.io
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
# value should match values.image version
appVersion: 6.4.2