---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: {{ template "name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  ports:
  - port: {{.Values.port}}
    name: {{.Values.port_name}}
  clusterIP: None
  selector:
    name: {{.Values.port_selector}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service_name}}
  labels:
    app: {{.Values.cluster_name}}
    name: {{ .Values.master_name}}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  ports:
  - port: {{.Values.cluster_port}}
    name: {{.Values.cluster_port_name}}
    protocol: TCP
  clusterIP: None
  selector:
    app: {{.Values.name}}

---
{{- if .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.name}}
          servicePort: {{.Values.port}}

{{- end }}
